[project]
name = "flux-contract"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.payment-stream-security]
path = "contracts/payment-stream-security.clar"
depends_on = []

[contracts.streaming-payments]
path = "contracts/streaming-payments.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
